[info]

name = "Openbot" # change this to your bot's name
description = "A Free, Customisable, Open-Source Discord Bot" # change this to your bot's description
invite = "Bot Invite Link" # change this to your bot's invite link

[embed]

color = "00FF00"

[admin]

users = [
    "609463800818827264"
]

guilds = [
    "1027539359945203722"
]